# Generated by Django 2.2.6 on 2019-10-04 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsbadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread'), ('TRASH', 'Trash')], default='UNREAD', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 2, 32, 16, 27872)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 2, 32, 16, 29904)),
        ),
    ]
