# Generated by Django 2.2.6 on 2019-10-09 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsbadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouch',
            name='status',
            field=models.CharField(blank=True, choices=[('TRASH', 'Trash'), ('READ', 'Read'), ('UNREAD', 'Unread')], default='UNREAD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('TRASH', 'Trash'), ('READ', 'Read'), ('UNREAD', 'Unread')], default='UNREAD', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 14, 48, 38, 19793)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 14, 48, 38, 19793)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 14, 48, 38, 19793)),
        ),
    ]
