# Generated by Django 2.2.6 on 2019-10-11 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsbadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_count', models.IntegerField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('TRASH', 'Trash')], default='UNREAD', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 11, 21, 25, 34, 547346)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 11, 21, 25, 34, 547346)),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='status',
            field=models.CharField(blank=True, choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('TRASH', 'Trash')], default='UNREAD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 11, 21, 25, 34, 551419)),
        ),
    ]
