# Generated by Django 2.2.6 on 2019-10-12 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsbadmin', '0002_auto_20191011_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('TRASH', 'Trash'), ('READ', 'Read')], default='UNREAD', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 14, 28, 32, 731062)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 14, 28, 32, 731062)),
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='status',
            field=models.CharField(blank=True, choices=[('UNREAD', 'Unread'), ('TRASH', 'Trash'), ('READ', 'Read')], default='UNREAD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newslettermessage',
            name='email_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 14, 28, 32, 733090)),
        ),
    ]
