# Generated by Django 2.2.6 on 2019-10-05 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsbadmin', '0004_auto_20191005_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 17, 59, 45, 255433)),
        ),
        migrations.AlterField(
            model_name='event',
            name='events_title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 17, 59, 45, 257428)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(max_length=150),
        ),
    ]
