# Generated by Django 2.2.6 on 2019-10-05 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsbadmin', '0005_auto_20191005_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('TRASH', 'Trash'), ('READ', 'Read')], default='UNREAD', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 17, 59, 48, 6743)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 17, 59, 48, 9734)),
        ),
    ]
