# Generated by Django 2.2.6 on 2019-10-05 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsbadmin', '0009_auto_20191006_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread'), ('TRASH', 'Trash')], default='UNREAD', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 1, 13, 9, 375608)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 1, 13, 9, 376605)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 1, 13, 9, 376605)),
        ),
    ]
