# Generated by Django 2.2.6 on 2019-10-06 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccsbadmin', '0010_auto_20191006_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_image',
            field=models.ImageField(max_length=200, upload_to='aboutus'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('TRASH', 'Trash'), ('READ', 'Read'), ('UNREAD', 'Unread')], default='UNREAD', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 0, 58, 31, 585403)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 0, 58, 31, 585403)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 0, 58, 31, 589394)),
        ),
    ]
